你好👋ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
	$(CC) vorpal.c -o vorpal -Wall -Wextra -pedantic -std=c99
